services:
  nginx:
    image: nginx:alpine
    container_name: driveway-hub-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - driveway-hub-network

  app:
    ports: []  # Remove external port binding, only accessible via nginx

networks:
  driveway-hub-network:
    driver: bridge
